---

- name: Create a template file for iTrust build job
  template: src=iTrust.xml dest=/tmp/itrust_temp.xml

- name: Copy db.properties
  template: src=db.properties.j2 dest=/tmp/db.properties

- name: Copy hibernate.properties
  template: src=hibernate.properties.j2 dest=/tmp/hibernate.properties

- name: Check if job already made
  shell: "java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ list-jobs --username {{jenkins_username}} --password {{jenkins_password}}"
  register: jenkins_check

- name: Create Job
  shell: "java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ create-job {{jenkins_iTrust}} < /tmp/itrust_temp.xml --username {{jenkins_username}} --password {{jenkins_password}}"
  when: jenkins_check.stdout.find(jenkins_iTrust)==-1

- name: Build iTrust job
  shell: "java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ build {{jenkins_iTrust}} --username {{jenkins_username}} --password {{jenkins_password}} -s"
