---
- name: Install the package "redis-server"
  apt:
    name: redis-server
    state: present

- name: Delete bind line in redis.conf file
  lineinfile: dest=/etc/redis/redis.conf
              state=absent
              regexp='bind 127.0.0.1'

- name: Restart the redis-server service
  service:
    name: redis-server
    state: restarted