---
- hosts: locals
  become: false
  vars:
    instance_type: t2.micro
    security_group: ansible-webserver 
    image: ami-79873901 
    keypair: ec2checkbox 
    region: us-west-2 
    count: 1

  tasks:
    - name: Create key
      ec2_key:
        name: "{{keypair}}"
        region: us-west-2
        key_material: "{{ item }}"
      with_file: ~/.ssh/id_rsa.pub
      register: ec2_key_result

    - name: Launch the new EC2 Instance
      local_action: ec2 
                    group={{ security_group }} 
                    instance_type={{ instance_type}} 
                    image={{ image }} 
                    wait=true 
                    region={{ region }} 
                    keypair={{ keypair }}
                    count={{count}}
      register: ec2
    # - debug: var=item
    # - debug: var=ec2
    - debug: var=ec2.instances[0].public_ip

    - name: Wait for SSH to come up
      local_action: wait_for 
                    host={{ ec2.instances[0].public_ip }} 
                    port=22 
                    state=started

    - name: Add new ec2 to inventory
      add_host: >
        name=ec2checkbox
        groups=ec2checkbox
        ansible_ssh_host="{{ ec2.instances[0].public_ip }}"
        ansible_ssh_user=ubuntu
        ansible_ssh_private_key_file="~/.ssh/id_rsa" 

    - pause: 
        minutes: 1

- hosts: ec2checkbox
  become: yes
  gather_facts: false
  tasks: 
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: ec2checkbox
  become: yes
  roles:
    - env
    - git
    - python
    - mongodb
    - nginx
    - nodejs
    - checkbox_conf

 
