---
- hosts: ec2itrust

  become: yes

  roles:
    - java
    - maven
    - git
    - mysql

  tasks:
  - include_vars: secrets.yml
  - name: Cloning iTrust2 repo
    git: 
      repo: https://{{ git_token }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v2
      dest: /home/vagrant/code

  - name: Configuring Hibernate for DB
    template:
      src: ./templates/db.properties.template
      dest: /home/vagrant/code/iTrust2/src/main/java/db.properties

  - name: Configuring Hibernate for Hibernate
    template:
      src: ./templates/hibernate.properties.template
      dest: /home/vagrant/code/iTrust2/src/main/resources/hibernate.properties

  - name: Configuring Hibernate for Email
    template:
      src: ./templates/email.properties.template
      dest: /home/vagrant/code/iTrust2/src/main/java/email.properties

  - name: Run iTrust application
    shell: cd /home/vagrant/code/iTrust2/ && ( (nohup mvn jetty:run) & )
