---
- hosts: locals
  become: false
  vars:
    instance_type: t2.micro
    security_group: ansible-webserver 
    image: ami-79873901 
    keypair: ec2itrust 
    region: us-west-2 
    count: 1

  tasks:
    - name: Create key
      ec2_key:
        aws_access_key: '{{aws_access_key}}'
        aws_secret_key: '{{aws_secret_key}}'
        name: "{{keypair}}"
        region: us-west-2
      register: ec2_key

    # - debug: var=ec2_key 
    - name: Save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="/var/lib/jenkins/aws-private2.pem" mode=0600 owner="jenkins" group="jenkins"
      when: ec2_key.changed


    - name: Launch the new EC2 Instance
      local_action: ec2 
                    aws_access_key={{aws_access_key}}
                    aws_secret_key={{aws_secret_key}}
                    group={{ security_group }} 
                    instance_type={{ instance_type}} 
                    image={{ image }} 
                    wait=true 
                    region={{ region }} 
                    keypair={{ keypair }}
                    count={{count}}
      register: ec2
    # - debug: var=item
    # - debug: var=ec2
    - debug: var=ec2.instances[0].public_ip

    - name: Wait for SSH to come up
      local_action: wait_for 
                    host={{ ec2.instances[0].public_ip }} 
                    port=22 
                    state=started

    - name: Add new ec2 to inventory
      add_host: >
        name=ec2itrust
        groups=ec2itrust
        ansible_ssh_host="{{ ec2.instances[0].public_ip }}"
        ansible_ssh_user=ubuntu
        ansible_ssh_private_key_file="~/aws-private2.pem" 

    - pause: 
        minutes: 1

- hosts: ec2itrust
  become: yes
  gather_facts: false
  tasks: 
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Install Packages
      apt: name= {{ item }} update_cache=yes state=latest
      with_items:
        - npm

- hosts: ec2itrust
  become: yes
  roles:
    - env
    - java
    - maven
    - git
    - mysql

  tasks:
  - include_vars: secrets.yml
  - name: Cloning iTrust2 repo
    git: 
      repo: https://{{ git_token }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v2
      dest: /home/vagrant/code

  - name: Configuring Hibernate for DB
    template:
      src: ./templates/db.properties.template
      dest: /home/vagrant/code/iTrust2/src/main/java/db.properties

  - name: Configuring Hibernate for Hibernate
    template:
      src: ./templates/hibernate.properties.template
      dest: /home/vagrant/code/iTrust2/src/main/resources/hibernate.properties

  - name: Configuring Hibernate for Email
    template:
      src: ./templates/email.properties.template
      dest: /home/vagrant/code/iTrust2/src/main/java/email.properties

  - name: Run iTrust application
    shell: cd /home/vagrant/code/iTrust2/ && mvn process-test-classes

  - name: Run iTrust application
    shell: cd /home/vagrant/code/iTrust2/ && ( (nohup mvn jetty:run) & )
