---
- hosts: all
  become: yes
  roles:
    - git
    - env

  vars: 
    cb_path: '/home/vagrant/checkbox'
    mongo_user: 'admin'
 
  tasks:
  - name: Clone Checkbox IO application
    git: 
      repo: https://github.com/vjhebbar/checkbox.io.git
      dest: /home/vagrant/checkbox

  - name: install pip
    apt:
     name: python3-pip
     state: installed

  - name: install pymongo
    pip:
     name: pymongo
     state: present

  - name: Adding the key for Mongodb
    apt_key:
      url: "https://www.mongodb.org/static/pgp/server-3.6.asc"
      state: present

  - name: Add the mongodb repo
    apt_repository: 
      repo: "deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" 
      state: present
  
  - debug:
      msg: "{{ansible_env.MAIL_USER}}"
 
  - name: Install mongodb
    apt:
      name: mongodb-org
      state: installed
      update_cache: yes

  - name: Start mongodb service
    service:
      name: mongod
      state: started

  - name: Install nginx
    apt:
      name: nginx
      state: installed
  
#  - name: Add NodeJS GPG key
#    apt_key:
#      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

#  - name: Add NodeJS Repo
#    apt_repository:
#      repo: "deb https://deb.nodesource.com/setup_9.x {{ ansible_distribution_release }} main"
#      state: present

  - name: Install NodeJS
    apt:
      name: nodejs-legacy
      state: present
      update_cache: yes

  - name: Install NPM
    apt:
      name: npm
      state: present
      update_cache: yes
   
  - name: Install node dependencies
    npm:
      path: /home/vagrant/checkbox/server-side/site/
      state: present


  - name: Add mongodb users
    mongodb_user:
      database: admin
      name: '{{mongo_user}}'
      password: '{{mongo_pwd}}'
      state: present 

  - name: Copy the nginx configuration file
    copy: 
      src: '/home/vagrant/checkbox/local-conf/nginx.conf'
      dest: '/etc/nginx/nginx.conf'
      remote_src: yes  
      force: yes

  - name: Fetch nginx configuration file
    run_once: true
    fetch:
      src: '/home/vagrant/checkbox/local-conf/default'
      dest: '/home/vagrant/tmp/'
      flat: yes

  - name: Copy the nginx default files
    template: 
      src: '/home/vagrant/tmp/default'
      dest: '/etc/nginx/sites-available/default'  
      force: yes

  - name: reload nginx
    command: nginx -s reload

  - name: Start NodeJS Server
    command: 'nohup nodejs server.js &'
    args:
      chdir: '/home/vagrant/checkbox/server-side/site'
 

