---
- hosts: all
  gather_facts: no
  become: yes
  
  tasks:

  - name: install maven (and other packages if needed)
    apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items:
      - maven
      - git

  - name: ensure required packages are installed for Java 7
    apt: name=python-software-properties

  - name: Add Java repository to sources
    apt_repository: repo='ppa:webupd8team/java'

  - name: Autoaccept license for Java
    action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections


  - name: Install Java 8
    apt: name=oracle-java8-installer force=yes
    
  - name: Downloading jenkins
    shell: wget -q -O - http://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -

  - name: Updating jenkins source list
    shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

  - name: Updating APT package cache
    action: apt update_cache=yes

  - name: Installing Jenkins
    apt:
      name: jenkins
      state: present
      install_recommends: yes
