---
- hosts: all
  become: yes
  vars_prompt: 
    - name: jenkins_username 
      prompt: "Enter your username" 
      private: no 
    - name: jenkins_password 
      prompt: "Enter your password" 
      private: yes
  vars:
    jenkins_ip: localhost
    jenkins_port: 8080
    jenkins_user: "jenkins"
    jenkins_home: "/var/lib/jenkins"
    jenkins:
      url_username: "{{jenkins_username}}"
      validate_certs: no
    jenkins_checkbox: checkboxJob

  roles: 
    - jenkins
    - checkbox_build
    