---
- hosts: localhost
  become: false
  vars:
    do_token: "{{ lookup('env', 'DOTOKEN') }}"
    instance_type: t2.micro
    security_group: ansible-webserver 
    image: ami-79873901 
    keypair: ec2main 
    region: us-west-2 
    count: 1
    jenkins_ip: localhost
    jenkins_port: 9090
    jenkins_user: "jenkins"
    jenkins_home: "/var/lib/jenkins"
    jenkins_checkbox: checkboxJob
    jenkins_iTrust: iTrustJob
    jenkins_iTrust_fuzz: iTrust-Fuzz-Job

  roles:
    - createVM
  tasks:
    - include_vars: secrets.yml
    # - debug: var=do_token
  
- hosts: iTrust-checkbox-jenkins-mysql
  become: yes
  gather_facts: false
  vars:
    host_key_checking: False
  remote_user: "root"
  connection: ssh
  tasks: 
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    
- hosts: iTrust-checkbox-jenkins-mysql
  become: yes
  vars:
    host_key_checking: False
    jenkins_ip: localhost
    jenkins_port: 9090
    jenkins_user: "jenkins"
    jenkins_home: "/var/lib/jenkins"
    jenkins_checkbox: checkboxJob
    jenkins_iTrust: iTrustJob
    jenkins_iTrust_fuzz: iTrust-Fuzz-Job
    jenkins_ec2_ip: "{{ hostvars['localhost']['jenkins_ec2_ipadd']}}"
    
  remote_user: "ubuntu"
  connection: ssh

#   vars:
#     jenkins_ip: localhost
#     jenkins_port: 9090
#     jenkins_user: "jenkins"
#     jenkins_home: "/var/lib/jenkins"
#     jenkins_checkbox: checkboxJob
#     jenkins_iTrust: iTrustJob
#     jenkins_iTrust_fuzz: iTrust-Fuzz-Job

  roles: 
    - dependencies
    - mysql
    - ansible
    - jenkins
    - checkbox_build
    - iTrust_build
  # tasks:
  #   - debug: var=jenkins_ec2_ip
   
