---
- hosts: localhost
  become: false
  vars:
    instance_type: t2.micro
    security_group: ansible-webserver 
    image: ami-79873901 
    keypair: ec2main 
    region: us-west-2 
    count: 1

  tasks:
    - name: Create key
      ec2_key:
        aws_access_key: '{{aws_access_key}}'
        aws_secret_key: '{{aws_secret_key}}'
        name: "{{keypair}}"
        region: us-west-2
      register: ec2_key

    # - debug: var=ec2_key 
    - name: Save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="~/aws-private3.pem" mode=0600
      when: ec2_key.changed


    - name: Launch the new EC2 Instance
      local_action: ec2 
                    aws_access_key={{aws_access_key}}
                    aws_secret_key={{aws_secret_key}}
                    group={{ security_group }} 
                    instance_type={{ instance_type}} 
                    image={{ image }} 
                    wait=true 
                    region={{ region }} 
                    keypair={{ keypair }}
                    count={{count}}
      register: ec2
    # - debug: var=item
    # - debug: var=ec2
    - debug: var=ec2.instances[0].public_ip

    - name: Wait for SSH to come up
      local_action: wait_for 
                    host={{ ec2.instances[0].public_ip }} 
                    port=22 
                    state=started

    - name: Add new ec2 to inventory
      add_host: >
        name=ec2main
        groups=ec2main
        ansible_ssh_host="{{ ec2.instances[0].public_ip }}"
        ansible_ssh_user=ubuntu
        ansible_ssh_private_key_file="~/aws-private3.pem" 
        ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

    - pause: 
        minutes: 1

- hosts: ec2main
  become: yes
  gather_facts: false
  tasks: 
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    
- hosts: ec2main
  become: yes

  vars:
    jenkins_ip: localhost
    jenkins_port: 8080
    jenkins_user: "jenkins"
    jenkins_home: "/var/lib/jenkins"
    jenkins_checkbox: checkboxJob
    jenkins_iTrust: iTrustJob

  roles: 
    - mysql
    - ansible
    - jenkins
    - checkbox_build
    - iTrust_build
    #
   