---
- hosts: all
  become: yes
  vars_prompt: 
    - name: jenkins_username 
      prompt: "Enter your username" 
      private: no 
    - name: jenkins_password 
      prompt: "Enter your password" 
      private: yes

  roles: 
    - jenkins
    
   


    # - name: Create first Jenkins job
    #   jenkins_job:
    #     config: "{{ lookup('template', 'templates/test.xml.j2') }}"
    #     name: test
    #     token: asdfasfasfasdfasdfadfasfasdfasdfc
    #     url: http://192.168.17.111:8080
    #     user: admin
    #       