---
- hosts: all
  become: yes

  vars:
    jenkins_ip: localhost
    jenkins_port: 8080
    jenkins_user: "jenkins"
    jenkins_home: "/var/lib/jenkins"
    jenkins_checkbox: checkboxJob
    jenkins_iTrust: iTrustJob

  roles: 
    # - mysql
    # - ansible
    # - jenkins
    # - checkbox_build
    # - iTrust_build
    #
  tasks:
    - name: Upload directory to Deployment host
      copy: src=./provision dest=~/deploy directory_mode=yes 