---
  - name: Clone Checkbox IO application
    git: 
      repo: https://github.com/vjhebbar/checkbox.io.git
      dest: /home/vagrant/checkbox

  - name: Start mongodb service
    service:
      name: mongod
      state: started

  - name: Add mongodb users
    mongodb_user:
      database: admin
      name: '{{mongo_user}}'
      password: '{{mongo_pwd}}'
      state: present 

  - name: Copy the nginx configuration file
    copy: 
      src: '/home/vagrant/checkbox/local-conf/nginx.conf'
      dest: '/etc/nginx/nginx.conf'
      remote_src: yes  
      force: yes

  - name: Fetch nginx configuration file
    run_once: true
    fetch:
      src: '/home/vagrant/checkbox/local-conf/default'
      dest: '/home/vagrant/tmp/'
      flat: yes

  - name: Copy the nginx default files
    template: 
      src: '/home/vagrant/tmp/default'
      dest: '/etc/nginx/sites-available/default'  
      force: yes

  - name: reload nginx
    command: nginx -s reload

  - name: Start NodeJS Server
    command: 'nohup nodejs server.js &'
    args:
      chdir: '/home/vagrant/checkbox/server-side/site'
 

