- job:
    name: "{{jenkins_iTrust}}"
    description: "built by job builder"
    builders:
      - shell: |
            git clone https://{{ git_token | urlencode }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v2 
            sudo cp /tmp/db.properties iTrust2-v2/iTrust2/src/main/java/db.properties 
            sudo cp /tmp/hibernate.properties iTrust2-v2/iTrust2/src/main/resources/hibernate.properties 
            sudo cp /tmp/email.properties iTrust2-v2/iTrust2/src/main/java/email.properties 
            sudo cp /tmp/pom-data.xml iTrust2-v2/iTrust2/pom-data.xml 
            cd iTrust2-v2/iTrust2 
            sudo mvn process-test-classes -f pom-data.xml 
            sudo mvn clean test verify checkstyle:checkstyle
    publishers:
      - jacoco
    wrappers:
    - workspace-cleanup
    # - timeout:
    #     timeout: 1
    #     fail: true
