FROM nginx:alpine
WORKDIR /usr/src/app
COPY ./checkbox.io ./
COPY ./checkbox.io/local-conf/default /etc/nginx/sites-available/default
COPY ./checkbox.io/local-conf/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
