FROM mongo:3.6.3
RUN mongod --bind_ip_all --fork --syslog
RUN mongo admin --eval "db.createUser({ user: 'admin', pwd: 'admin', roles: [ { role: 'userAdminAnyDatabase', db: 'admin' } ] })" 
RUN touch test.log
CMD ["mongod","--bind_ip_all"]
