---
- include_vars: ../../../secrets.yml
- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes 
  with_items:
    - maven
    - git
    - npm
    - nodejs-legacy

- name: ensure required packages are installed for Java 8
  apt: name=python-software-properties

- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java 8
  apt: name=oracle-java8-installer force=yes
    
- name: Downloading jenkins
  apt_key:
    url: "http://pkg.jenkins.io/debian/jenkins-ci.org.key"
    state: present
    validate_certs: no

- name: Updating jenkins source list
  shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Updating APT package cache
  action: apt update_cache=yes

- name: Installing Jenkins
  apt:
    name: jenkins
    state: present
    install_recommends: yes

  ## Fix to bypass setup wizard https://github.com/geerlingguy/ansible-role-jenkins/issues/50
- name: Create a directory for Groovy
  file:
    path: "/var/lib/jenkins/init.groovy.d"
    state: directory
    mode: 0777
 
- name: Create a user for jenkins server
  template: 
    src: jenkins_script.groovy.j2 
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy 
    mode: 0777

- name: Restart Jenkins and add user
  service:
    name: jenkins
    state: restarted

- wait_for:
    timeout: 15

- name: Remove script to avoid duplicate users
  file:
    path: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
    state: absent

- wait_for:
    timeout: 30
   
- name: Install Jenkin Plugins
  jenkins_plugin:
    name: "{{ item }}"
    params: "{{ jenkins }}"
    url_password: "{{jenkins_password}}"
    url: "http://{{jenkins_ip}}:{{jenkins_port}}"
  with_items:
    - github
    - postbuild-task
    - ws-cleanup
    - postbuildscript
   
- name: Restart Jenkins 
  service:
    name: jenkins
    state: restarted

- wait_for:
    timeout: 30
