- job:
    name: "{{jenkins_checkbox}}"
    description: "build checkbox and install dependencies using new package.json"
    builders:
      - shell: |
          sudo git clone https://github.com/chrisparnin/checkbox.io
          cd checkbox.io/server-side/site
          sudo cp tmp/package.json ./
          sudo npm install
          sudo node main.js server.js
          sudo node test.js
          # get reports
    publishers: 
      - post-tasks:
          script: |
            #download fromm server and extract  
      - html-publisher:
          name: "Coverage report"
          dir: "lcov-report"