- job:
    name: "{{jenkins_checkbox}}"
    description: "build checkbox and install dependencies using new package.json"
    builders:
      - shell: |
          sudo git clone https://github.com/rohilshah95/checkbox.io
          cd checkbox.io/server-side/site
          sudo npm install
    publishers:
      - post-tasks:
        - matches:
          - log-text: 
            operator: AND
          escalate-status: false
          run-if-job-successful: false
          script: |
              sudo git remote add production https://{{ git_token_com | urlencode }}@github.com/rohilshah95/checkbox.io
              sudo cp /tmp/post-receive checkbox.io/.git/hooks/post-receive
              sudo chmod 777 checkbox.io/.git/hooks/post-receive
              sudo touch test
              sudo git add . 
              sudo git config --global user.email "rgshah3@gmail.com"
              sudo git config --global user.name "Rohil Shah"
              sudo git commit -m "push to production"
              sudo git push production master
    wrappers:
      - workspace-cleanup