- job:
    name: "{{jenkins_checkbox}}"
    description: "build checkbox and install dependencies using new package.json"
    builders:
      - shell: |
          sudo git clone https://{{ git_token_com | urlencode }}@github.com/rcoutin/checkbox.io
          sudo cp /tmp/server.js  checkbox.io/server-side/site/server.js
          cd checkbox.io/server-side/site
          sudo npm install
          cd ../..
          sudo git add -f server-side/site/server.js
          sudo git config --global user.email "rgshah3@gmail.com"
          sudo git config --global user.name "Rohil Shah"
          sudo git commit -m "push redis server ipaddress"
          sudo git push origin master
    publishers:
      - post-tasks:
        - matches:
          - log-text: 
            operator: AND
          escalate-status: false
          run-if-job-successful: false
          script: |
              cd checkbox.io
              sudo mkdir deploy
              cd deploy
              sudo mkdir production.git
              sudo mkdir production-www
              cd production.git
              sudo git init --bare 
              sudo cp /tmp/post-receive hooks/post-receive
              sudo chmod +x hooks/post-receive
              cd ../..
              sudo git remote add production file:///var/lib/jenkins/workspace/checkboxJob/checkbox.io/deploy/production.git
              sudo touch test2
              sudo git add . 
              sudo git config --global user.email "rgshah3@gmail.com"
              sudo git config --global user.name "Rohil Shah"
              sudo git commit -m "push to production"
              sudo git push production master

    wrappers:
      - workspace-cleanup