- job:
    name: "{{jenkins_checkbox}}"
    description: "build checkbox and install dependencies using new package.json"
    builders:
      - shell: |
          sudo git clone https://github.com/chrisparnin/checkbox.io
          cd checkbox.io/server-side/site
          sudo cp tmp/package.json ./
          sudo npm install
          sudo node main.js server.js
          sudo node test.js &
    publishers: 
      - post-tasks:
          script: |
            sudo sleep 10s
            sudo wget http://localhost:4004/coverage/download
            sudo unzip download -d /var/lib/jenkins/workspace/{{jenkins_checkbox}}/
      - html-publisher:
          name: "Coverage report"
          dir: "lcov-report"