---
- include_vars: ../../secrets.yml

- name: Exporting necessary environment variable
  shell: export ANSIBLE_HOST_KEY_CHECKING=False

- name: Create key
  ec2_key:
    aws_access_key: '{{aws_access_key}}'
    aws_secret_key: '{{aws_secret_key}}'
    name: "{{keypair}}"
    region: us-west-2
  register: ec2_key

# - debug: var=ec2_key 
- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest="~/aws-private3.pem" mode=0600
  when: ec2_key.changed


- name: Launch the new Jenkins and MySQL EC2 Instance
  local_action: ec2 
                aws_access_key={{aws_access_key}}
                aws_secret_key={{aws_secret_key}}
                group={{ security_group }} 
                instance_type={{ instance_type}} 
                image={{ image }} 
                wait=true 
                region={{ region }} 
                instance_tags=Name=jenkins-mysql
                keypair={{ keypair }}
                count={{count}}
  register: ec2_jenkins
# - debug: var=item
# - debug: var=ec2
- debug: var=ec2_jenkins.instances[0].public_ip

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ ec2_jenkins.instances[0].public_ip }} 
                port=22 
                state=started


- name: Fethching Public IP for existing jenkins instance
  set_fact: jenkins_ec2_ip="{{ec2_jenkins.instances[0].public_ip}}"
  when: ec2_jenkins.instances|length>0

# - name: Add new ec2 to inventory
#   add_host: >
#     name="{{ jenkins_ec2_ip }}"
#     groups=iTrust-checkbox-jenkins-mysql
#     ansible_ssh_host="{{ ec2_jenkins.instances[0].public_ip }}"
#     ansible_ssh_user=ubuntu
#     ansible_ssh_private_key_file="~/aws-private3.pem" 
#     ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

- name: Add the instance to group for installing Jenkins
  add_host:
    hostname: "{{ jenkins_ec2_ip }}"
    groupname: iTrust-checkbox-jenkins-mysql

- name: Add SSH fingerprints                                         
  shell: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts          
  with_items: 
    - "{{ jenkins_ec2_ip }}"