apiVersion: v1
kind: Service
metadata:
  name: checkbox-service
spec:
  selector:
      group: one  
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 3002
      nodePort: 30002
      name: nodejs
    - port: 6379
      nodePort: 30079
      name: rs
  type: NodePort
---
apiVersion: apps/v1         
kind: Deployment            
metadata:                   
  name: deploy-primary
spec:                       
  replicas: 3               
  selector:                             
    matchLabels:    
      group : one         
  template:                 
    metadata:               
     labels:
        group: one    
    spec:    
      containers:           
      - name: cb-back         
        image: gcr.io/vj04142018/cb-back:v3    
        env:
         - name: MONGO_IP
           value: "{{sec_ip_output.stdout}}"
      - name: cb-front
        image: gcr.io/vj04142018/cb-front:v3
        ports:
        - containerPort: 80 
      - name: redis-slave
        image: redis:latest
        command: ["redis-server"]
        args: ["--slaveof", "10.42.0.1", "6379"]
        # image: gcr.io/vj04142018/redis-slave:v1
        ports:
        - containerPort: 6379
