---
- name: Copy secondary deployment script
  copy:
    src: ./deploy_secondary.yml
    dest: /root/deploy_secondary.yml 

- name: Execute secondary deployment scripts
  command: kubectl create -f deploy_secondary.yml   

- name: Get IP of secondary services
  shell: "kubectl get pods -o wide | grep -v IP | awk '{ print $6}'"
  register: sec_ip_output

- set_fact:
    sec_ip = "{{sec_ip_output.stdout}}"

- name: Template primary deployment script
  template: 
    src: ./deploy_primary.yml
    dest: /root/deploy_primary.yml

- name: Execute primary deployment scripts
  command: kubectl create -f deploy_primary.yml