---
- name: clone iTrust
  git: repo=https://{{ git_token | urlencode }}@github.ncsu.edu/sshah14/iTrust2-v2 dest=/home/ubuntu/iTrust

- name: Copy db.properties
  template: 
    src: db.properties.j2 
    dest: /home/ubuntu/iTrust/iTrust2/src/main/java/db.properties/

- name: Copy email.properties
  template: 
    src: email.properties.template 
    dest: /home/ubuntu/iTrust/iTrust2/src/main/java/email.properties/

- name: Copy hibernate.properties
  template: 
    src: hibernate.properties.j2 
    dest: /home/ubuntu/iTrust/iTrust2/src/main/resources/hibernate.properties

- name: Copy package.json to iTrust directory
  copy:
    src: package.json
    dest: /home/ubuntu/iTrust/

- name: Copy fuzzing.js to iTrust directory
  copy:
    src: fuzzing.js
    dest: /home/ubuntu/iTrust/

- name: Add git config
  shell: git config --global user.email "rshah8@ncsu.edu"

- name: Add git config
  shell: git config --global user.name "Rohil Shah"

- name: Copy runFuzzing.js to iTrust directory
  template:
    src: templates/runFuzzing.js
    dest: /home/ubuntu/iTrust/

- name: Copy post commit files to iTrust hook
  template:
    src: templates/post-commit
    dest: /home/ubuntu/iTrust/.git/hooks/
    mode: 0777

- name: Install packages based on package.json.
  npm:
    path: /home/ubuntu/iTrust/

- name: Create iTrust job builder file
  template:
    src: templates/itrust-fuzz-job.yaml
    dest: jobs/

- name: Add the jobs
  shell: jenkins-jobs update jobs

- name: Creates directory
  file:
    path: /var/lib/jenkins/workspace/iTrust-Fuzz-Job
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Creates empty directory
  file:
    path: /var/lib/jenkins/workspace/iTrust-Fuzz-Job/iTrust2-v2
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Creates report directory
  file:
    path: /home/ubuntu/reports
    state: directory

- name: Copy report files to Jenkins home dir
  template:
    src: copyReport.js
    dest: /var/lib/jenkins/

- name: Copy package.json to Jenkins home dir
  copy:
    src: package.json
    dest: /var/lib/jenkins

- name: Install packages based on package.json.
  npm:
    path: "/var/lib/jenkins"

- name: run fuzzer job
  shell: node runFuzzing.js
  args:
    chdir: /home/ubuntu/iTrust

# - name: Build Jenkins Job for iTrust
  # shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ build {{ jenkins_iTrust_fuzz }} --username {{jenkins_username}} --password {{jenkins_password}} -s"